# Use Node.js LTS as base
FROM node:18

# Set working directory
WORKDIR /app

# Copy files
COPY package*.json ./
COPY . .

# Install dependencies
RUN npm install

# Expose port
EXPOSE 5000

# Run server
CMD ["npm", "run", "start"]
